// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmtz3nKsGyb853LHq244N7yLXErehbugY',
    appId: '1:590556310363:web:a10062d93447b29966487e',
    messagingSenderId: '590556310363',
    projectId: 'djaaferfirestore',
    authDomain: 'djaaferfirestore.firebaseapp.com',
    storageBucket: 'djaaferfirestore.firebasestorage.app',
    measurementId: 'G-MQM3WTFLWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXxsuSbraWYvFtCE-8cHLzilTYysjFN8U',
    appId: '1:590556310363:android:fa8ffbe70d38481366487e',
    messagingSenderId: '590556310363',
    projectId: 'djaaferfirestore',
    storageBucket: 'djaaferfirestore.firebasestorage.app',
  );
}
